export const ADD_CHANNEL = 'ADD_CHANNEL';
export const DELETE_CHANNEL = 'DELETE_CHANNEL';
export const UPDATE_CHANNEL_NAME = 'UPDATE_CHANNEL_NAME';
export const REQUEST_CHANNELS_ATTEMPT = 'REQUEST_CHANNELS_ATTEMPT';
export const REQUEST_CHANNELS_SUCCESS = 'REQUEST_CHANNELS_SUCCESS';
export const REQUEST_CHANNELS_ERROR = 'REQUEST_CHANNELS_ERROR';
